
GET http://localhost:3000/courses

###
GET http://localhost:3000/courses/1

###
POST http://localhost:3000/courses
Content-type: 'application/json'

{
    "id": 2,
    "name": "docker",
    "description": "curso de docker",
    "tags": [
        "docker", "devops"
    ]
}

###
PATCH http://localhost:3000/courses/203

content-type: 'application/json'

{
    "id": 2,
    "name": "docker",
    "description": "curso de docker",
    "tags": [
        "docker", "devops"
    ]
}

###
DELETE  http://localhost:3000/courses/203